# ===================================================================
# Spring Boot configuration.
#
# Cette configuration sera remplacée par le profil Spring que vous utilisez,
# par exemple application-dev.yml si vous utilisez le profil "dev".
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: ClientBatchLoader
    profiles:
        # La valeur commentée pour ʻactive` peut être remplacée par des profils Spring valides à charger.
        # Sinon, elle sera remplie par maven lors de la construction du fichier WAR.
        # Dans tous les cas, il peut être remplacé par la valeur `--spring.profiles.active` passée dans la ligne de commande ou `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

info:
    project:
        version: #project.version#

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

# ===================================================================
# Application specific properties
# ===================================================================