# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# Cette configuration surcharge le fichier application.yml.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: INFO
        clientBatchLoader: INFO

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

spring:
    devtools:
        restart:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./h2db/db/clientbatchloader-prod;
        username: ClientBatchLoader
        password:
    h2:
        console:
            enabled: true
    jpa:
        database-platform: clientbatchloader.config.FixedH2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    liquibase:
        contexts: prod

# ===================================================================
# Application specific properties
# ===================================================================

